#!/bin/bash
#
# Copyright (C) 2015 The AmmoniaOS Project
# Copyright (C) 2015 The SudaMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


PROJECTPATH=($ANDROID_BUILD_TOP/android
 $ANDROID_BUILD_TOP/build
 $ANDROID_BUILD_TOP/frameworks/base
 $ANDROID_BUILD_TOP/packages/apps/Browser
 $ANDROID_BUILD_TOP/packages/apps/Calendar
 $ANDROID_BUILD_TOP/packages/apps/CellBroadcastReceiver
 $ANDROID_BUILD_TOP/packages/apps/Contacts
 $ANDROID_BUILD_TOP/packages/apps/ContactsCommon
 $ANDROID_BUILD_TOP/packages/apps/DeskClock
 $ANDROID_BUILD_TOP/packages/apps/Dialer
 $ANDROID_BUILD_TOP/packages/apps/Eleven
 $ANDROID_BUILD_TOP/packages/apps/Mms
 $ANDROID_BUILD_TOP/packages/apps/LockClock
 $ANDROID_BUILD_TOP/packages/apps/InCallUI
 $ANDROID_BUILD_TOP/packages/apps/Settings
 $ANDROID_BUILD_TOP/packages/services/Telecomm
 $ANDROID_BUILD_TOP/packages/services/Telephony
 $ANDROID_BUILD_TOP/system/core
 $ANDROID_BUILD_TOP/system/extras/su
)

PROJECTLIST=(android.git
 android_build.git
 android_frameworks_base.git
 android_packages_apps_Browser.git
 android_packages_apps_Calendar.git
 android_packages_apps_CellBroadcastReceiver.git
 android_packages_apps_Contacts.git
 android_packages_apps_ContactsCommon.git
 android_packages_apps_DeskClock.git
 android_packages_apps_Dialer.git
 android_packages_apps_Eleven.git
 android_packages_apps_Mms-caf.git
 android_packages_apps_LockClock.git
 android_packages_apps_InCallUI.git
 android_packages_apps_Settings.git
 android_packages_services_Telecomm.git
 android_packages_services_Telephony.git
 android_system_core.git
 android_system_extras_su.git
)

count=0

function doMerge() {
	read -p "$1,Pull $2 ?[y]" Yes      
	if [ "$Yes" = y ]; then
		cd $1
        	git pull https://github.com/CyanogenMod/$2
        	git commit -a -m"Merge branch into sm-1.0"
        	git push https://github.com/SudaMod/$3 HEAD:sm-1.0
        	cd $ANDROID_BUILD_TOP
	fi
}

#public
for i in ${PROJECTPATH[@]}; do
	if [ ! -d $i ]; then
	        echo "$i,Did not find the directory!"
	        exit 1
        else       
		doMerge $i ${PROJECTLIST[count]} ${PROJECTLIST[count]}
                count=`expr $count + 1`;
	fi
done

#private
doMerge $ANDROID_BUILD_TOP/vendor/sm android_vendor_cm.git android_vendor_sm.git




