#!/bin/bash
#
# Copyright (C) 2015 The AmmoniaOS Project
# Copyright (C) 2015 The SudaMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


PROJECTPATH=($ANDROID_BUILD_TOP/android
 $ANDROID_BUILD_TOP/build
 $ANDROID_BUILD_TOP/frameworks/base
 $ANDROID_BUILD_TOP/packages/apps/Browser
 $ANDROID_BUILD_TOP/packages/apps/Calendar
 $ANDROID_BUILD_TOP/packages/apps/CellBroadcastReceiver
 $ANDROID_BUILD_TOP/packages/apps/Contacts
 $ANDROID_BUILD_TOP/packages/apps/ContactsCommon
 $ANDROID_BUILD_TOP/packages/apps/DeskClock
 $ANDROID_BUILD_TOP/packages/apps/Dialer
 $ANDROID_BUILD_TOP/packages/apps/Eleven
 $ANDROID_BUILD_TOP/packages/apps/Mms
 $ANDROID_BUILD_TOP/packages/apps/LockClock
 $ANDROID_BUILD_TOP/packages/apps/InCallUI
 $ANDROID_BUILD_TOP/packages/apps/Settings
 $ANDROID_BUILD_TOP/packages/services/Telecomm
 $ANDROID_BUILD_TOP/packages/services/Telephony
 $ANDROID_BUILD_TOP/system/core
 $ANDROID_BUILD_TOP/system/extras/su
 $ANDROID_BUILD_TOP/vendor/sm
)

PROJECTLIST=(android.git
 android_build.git
 android_frameworks_base.git
 android_packages_apps_Browser.git
 android_packages_apps_Calendar.git
 android_packages_apps_CellBroadcastReceiver.git
 android_packages_apps_Contacts.git
 android_packages_apps_ContactsCommon.git
 android_packages_apps_DeskClock.git
 android_packages_apps_Dialer.git
 android_packages_apps_Eleven.git
 android_packages_apps_Mms-caf.git
 android_packages_apps_LockClock.git
 android_packages_apps_InCallUI.git
 android_packages_apps_Settings.git
 android_packages_services_Telecomm.git
 android_packages_services_Telephony.git
 android_system_core.git
 android_system_extras_su.git
 android_vendor_cm.git
)

Yes='y'
count=0

for i in ${PROJECTPATH[@]}; do
	if [ ! -d $i ]; then
	        echo "$i,Did not find the directory!"
	        exit 1
        else
                read -p "$i,Pull ${PROJECTLIST[count]} ?[y]" Yes
                cd $i
                git pull https://github.com/CyanogenMod/${PROJECTLIST[count]}
                git commit -a -m"Merge branch into sm-1.0"
                git push https://github.com/SudaMod/${PROJECTLIST[count]} HEAD:sm-1.0
                cd $ANDROID_BUILD_TOP
                count=`expr $count + 1`;
	fi
done
